services:

  localstack:
    image: localstack/localstack:3.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - FILES_BUCKET=test-bucket
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/var/lib/localstack
    volumes:
      - ./localstack-data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/cors.json:/etc/localstack/init/ready.d/cors.json"
      - "./scripts/init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4566/_localstack/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:15.3-alpine
    container_name: flowdesk_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
     - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: flowdesk_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: flowdesk_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - ACCESS_TOKEN_EXPIRY=${ACCESS_TOKEN_EXPIRY}
      - REFRESH_TOKEN_EXPIRY=${REFRESH_TOKEN_EXPIRY}
      - STORAGE_BACKEND=s3
      - STORAGE_LOCAL_DIR=uploads
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - FILES_BUCKET=test-bucket
      - AWS_ENDPOINT_URL=http://localstack:4566
      - MIN_PART_SIZE_BYTES=5242880
      - ALLOWED_EXTENSIONS=pdf,png,jpg,jpeg,doc,docx,xls,xlsx,csv,txt,zip
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
      - SMTP_USER=
      - SMTP_PASSWORD=
      - SMTP_FROM=no-reply@flowdesk.com
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./app:/app/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build: .
    container_name: flowdesk_worker
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - ACCESS_TOKEN_EXPIRY=${ACCESS_TOKEN_EXPIRY}
      - REFRESH_TOKEN_EXPIRY=${REFRESH_TOKEN_EXPIRY}
      - STORAGE_BACKEND=s3
      - STORAGE_LOCAL_DIR=uploads
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - FILES_BUCKET=test-bucket
      - AWS_ENDPOINT_URL=http://localstack:4566
      - MIN_PART_SIZE_BYTES=5242880
      - ALLOWED_EXTENSIONS=pdf,png,jpg,jpeg,doc,docx,xls,xlsx,csv,txt,zip
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
      - SMTP_USER=
      - SMTP_PASSWORD=
      - SMTP_FROM=no-reply@flowdesk.com
    command: celery -A app.workers.celery_app worker --loglevel=info -P solo
    volumes:
      - ./app:/app/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: flowdesk_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api

  mailpit:
    image: axllent/mailpit:v1.15
    container_name: flowdesk_mailpit
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"


volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
