"""team and members models

Revision ID: 0fa609bb7e67
Revises: 90797c1f1567
Create Date: 2026-07-13 12:15:16.353408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa609bb7e67'
down_revision: Union[str, None] = '90797c1f1567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # 1. Drop existing composite primary key constraint on task_assignees
    op.drop_constraint('task_assignees_pkey', 'task_assignees', type_='primary')

    # 2. Add id column, populate it, and set as primary key
    op.add_column('task_assignees', sa.Column('id', sa.UUID(), nullable=True))
    op.execute("UPDATE task_assignees SET id = gen_random_uuid() WHERE id IS NULL")
    op.alter_column('task_assignees', 'id', nullable=False)
    op.create_primary_key('task_assignees_pkey', 'task_assignees', ['id'])

    # 3. Add team_id and assignee_type, alter user_id to nullable
    op.add_column('task_assignees', sa.Column('team_id', sa.UUID(), nullable=True))
    op.add_column('task_assignees', sa.Column('assignee_type', sa.String(), nullable=False, server_default='USER'))
    op.alter_column('task_assignees', 'assignee_type', server_default=None)

    op.alter_column('task_assignees', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_tasks_assignee', table_name='task_assignees')
    op.create_index('idx_tasks_assignee_team', 'task_assignees', ['team_id'], unique=False)
    op.create_index('idx_tasks_assignee_user', 'task_assignees', ['user_id'], unique=False)
    op.create_foreign_key(None, 'task_assignees', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_assignees', type_='foreignkey')
    op.drop_index('idx_tasks_assignee_user', table_name='task_assignees')
    op.drop_index('idx_tasks_assignee_team', table_name='task_assignees')
    op.create_index('idx_tasks_assignee', 'task_assignees', ['user_id'], unique=False)
    op.alter_column('task_assignees', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)

    # Revert to composite primary key
    op.drop_constraint('task_assignees_pkey', 'task_assignees', type_='primary')
    op.create_primary_key('task_assignees_pkey', 'task_assignees', ['task_id', 'user_id'])

    op.drop_column('task_assignees', 'assignee_type')
    op.drop_column('task_assignees', 'team_id')
    op.drop_column('task_assignees', 'id')
    op.drop_table('team_members')
    op.drop_table('teams')
    # ### end Alembic commands ###

