"""custom statuses and workflow rules

Revision ID: 21cce3681ad4
Revises: f8e3f9479b12
Create Date: 2026-07-13 14:24:18.907978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21cce3681ad4'
down_revision: Union[str, None] = 'f8e3f9479b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_project_statuses_project_name')
    )
    op.create_index('ix_project_statuses_org_id', 'project_statuses', ['org_id'], unique=False)
    op.create_index('ix_project_statuses_project_id', 'project_statuses', ['project_id'], unique=False)
    op.create_table('workflow_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=False),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'from_status', 'to_status', name='uq_workflow_rules_transition')
    )
    op.create_index('ix_workflow_rules_org_id', 'workflow_rules', ['org_id'], unique=False)
    op.create_index('ix_workflow_rules_project_id', 'workflow_rules', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_rules_project_id', table_name='workflow_rules')
    op.drop_index('ix_workflow_rules_org_id', table_name='workflow_rules')
    op.drop_table('workflow_rules')
    op.drop_index('ix_project_statuses_project_id', table_name='project_statuses')
    op.drop_index('ix_project_statuses_org_id', table_name='project_statuses')
    op.drop_table('project_statuses')
    # ### end Alembic commands ###
