"""index & automation rule model

Revision ID: 849021703e4d
Revises: d51374275fd4
Create Date: 2026-07-09 11:47:21.003884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '849021703e4d'
down_revision: Union[str, None] = 'd51374275fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trigger_event', sa.String(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('action_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_automation_rules_org_id', 'automation_rules', ['org_id'], unique=False)
    op.create_index('idx_automation_rules_project_id', 'automation_rules', ['project_id'], unique=False)
    op.create_table('task_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_events_unprocessed', 'task_events', ['processed', 'created_at'], unique=False, postgresql_where=sa.text('processed = false'))
    op.create_index('ix_task_events_org_id', 'task_events', ['org_id'], unique=False)
    op.create_index('ix_task_events_processed', 'task_events', ['processed'], unique=False)
    op.create_index('ix_task_events_task_id', 'task_events', ['task_id'], unique=False)
    op.create_unique_constraint(None, 'invitations', ['token'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'invitations', type_='unique')
    op.drop_index('ix_task_events_task_id', table_name='task_events')
    op.drop_index('ix_task_events_processed', table_name='task_events')
    op.drop_index('ix_task_events_org_id', table_name='task_events')
    op.drop_index('idx_task_events_unprocessed', table_name='task_events', postgresql_where=sa.text('processed = false'))
    op.drop_table('task_events')
    op.drop_index('idx_automation_rules_project_id', table_name='automation_rules')
    op.drop_index('idx_automation_rules_org_id', table_name='automation_rules')
    op.drop_table('automation_rules')
    # ### end Alembic commands ###
