"""task watchers table

Revision ID: c2bf00cfbca5
Revises: 21cce3681ad4
Create Date: 2026-07-13 14:41:28.549197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2bf00cfbca5'
down_revision: Union[str, None] = '21cce3681ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_watchers',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'user_id'),
    sa.UniqueConstraint('task_id', 'user_id', name='uq_task_watchers_task_user')
    )
    op.create_index('ix_task_watchers_org_id', 'task_watchers', ['org_id'], unique=False)
    op.create_index('ix_task_watchers_task_id', 'task_watchers', ['task_id'], unique=False)
    op.create_index('ix_task_watchers_user_id', 'task_watchers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_watchers_user_id', table_name='task_watchers')
    op.drop_index('ix_task_watchers_task_id', table_name='task_watchers')
    op.drop_index('ix_task_watchers_org_id', table_name='task_watchers')
    op.drop_table('task_watchers')
    # ### end Alembic commands ###
