"""notification fields nullable

Revision ID: d51374275fd4
Revises: 22d3551c0df1
Create Date: 2026-07-02 17:35:38.280859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51374275fd4'
down_revision: Union[str, None] = '22d3551c0df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'actor_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('notifications', 'entity_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notifications', 'entity_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'entity_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('notifications', 'entity_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notifications', 'actor_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
